In [1]:
import pandas as pd
import numpy as np

# heart.csv

In [2]:
df = pd.read_csv("/Users/harshilpatel/Desktop/Healthcare-Monitoring-Platform/data/raw/heart.csv")

In [3]:
print(df.head())

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2
1   53    1   0       140   203    1        0      155      1      3.1      0
2   70    1   0       145   174    0        1      125      1      2.6      0
3   61    1   0       148   203    0        1      161      0      0.0      2
4   62    0   0       138   294    1        1      106      0      1.9      1

   ca  thal  target
0   2     3       0
1   0     3       0
2   0     3       0
3   1     3       0
4   3     2       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [5]:
df.shape

(1025, 14)

In [6]:
print(df.isnull().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
print(df.describe())

               age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000
mean     54.434146     0.695610     0.942439   131.611707   246.00000
std       9.072290     0.460373     1.029641    17.516718    51.59251
min      29.000000     0.000000     0.000000    94.000000   126.00000
25%      48.000000     0.000000     0.000000   120.000000   211.00000
50%      56.000000     1.000000     1.000000   130.000000   240.00000
75%      61.000000     1.000000     2.000000   140.000000   275.00000
max      77.000000     1.000000     3.000000   200.000000   564.00000

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000
mean      0.149268     0.529756   149.114146     0.336585     1.071512
std       0.356527     0.527878    23.005724     0.472772     1.175053
min       0.000000     0.000000    71.000000     0.000000     0.000000
25%       0.000000     0.000000   132.000000     0.000000     0.000000
50%       0.000000     1.000000   152.000000     0.000000     0.800000
75%       0.000000     1.000000   166.000000     1.000000     1.800000
max       1.000000     2.000000   202.000000     1.000000     6.200000

             slope           ca         thal       target
count  1025.000000  1025.000000  1025.000000  1025.000000
mean      1.385366     0.754146     2.323902     0.513171
std       0.617755     1.030798     0.620660     0.500070
min       0.000000     0.000000     0.000000     0.000000
25%       1.000000     0.000000     2.000000     0.000000
50%       1.000000     0.000000     2.000000     1.000000
75%       2.000000     1.000000     3.000000     1.000000
max       2.000000     4.000000     3.000000     1.000000

In [7]:
df_cleaned = df.drop(columns=['slope','ca','thal'])

In [10]:
df_cleaned.to_csv('cleaned_data.csv',index=False)

In [21]:
data = pd.read_csv('/Users/harshilpatel/Desktop/Healthcare-Monitoring-Platform/data/processed/cleaned_data.csv')

In [23]:
data.rename(columns={'trestbps':'test_bps','thalach':'max_heart_rate'},inplace=True)

In [24]:
data.to_csv('cleaned_data.csv',index=False)

# wearable_sensor.csv

In [12]:
sensor = pd.read_csv('/Users/harshilpatel/Desktop/Healthcare-Monitoring-Platform/data/raw/wearable_sensor_data.csv')

In [14]:
print(sensor.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Timestamp                500 non-null    object
 1   Heart Rate (bpm)         500 non-null    int64
 2   Respiration Rate (bpm)   500 non-null    int64
 3   Body Temperature (°C)    500 non-null    float64
 4   Motion Activity (Level)  500 non-null    int64
 5   Activity Type            500 non-null    object
 6   Injury Risk Level        500 non-null    int64
dtypes: float64(1), int64(4), object(2)
memory usage: 27.5+ KB
None

In [17]:
sensor.rename(columns={'Heart Rate (bpm)':'Heart_Rate','Respiration Rate (bpm)':'Resp_rate','Body Temperature (°C)':'Body_temp','Motion Activity (Level)':'Motion_activity'},inplace=True)

In [18]:
sensor.head()

,Timestamp,Heart_Rate,Resp_rate,Body_temp,Motion_activity,Activity Type,Injury Risk Level
0,2024-12-18 10:00:00,162,24,36.494238,3,Cycling,0
1,2024-12-18 10:00:01,111,18,38.054979,1,Walking,1
2,2024-12-18 10:00:02,152,15,37.696473,2,Running,2
3,2024-12-18 10:00:03,74,24,37.355357,1,Walking,0
4,2024-12-18 10:00:04,166,12,36.961193,0,Rest,0

In [20]:
sensor.describe()

       Heart_Rate   Resp_rate   Body_temp  Motion_activity  Injury Risk Level
count  500.000000  500.000000  500.000000       500.000000         500.000000
mean   118.940000   20.352000   37.318518         1.478000           0.386000
std     35.188191    5.289239    0.701761         1.127856           0.664746
min     60.000000   12.000000   36.111117         0.000000           0.000000
25%     89.000000   16.000000   36.690733         0.000000           0.000000
50%    119.000000   20.000000   37.350380         1.000000           0.000000
75%    151.000000   25.000000   37.930589         3.000000           1.000000
max    179.000000   29.000000   38.495042         3.000000           2.000000